gui:
  screenMode: 'half' # one of 'normal' | 'half' | 'full' default is 'normal'
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  expandFocusedSidePanel: true
  showBottomLine: false
  mainPanelSplitMode: 'vertical' # one of 'horizontal' | 'flexible' | 'vertical' default 'flexible'
  showFileTree: false

keybinding:
  universal:
    return: 'q' # return to previous menu, will quit if there's nowhere to return

