gui:
  windowSize: 'normal' # one of 'normal' | 'half' | 'full' default is 'normal'
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  expandFocusedSidePanel: true
  showBottomLine: false

keybinding:
  universal:
    return: 'q' # return to previous menu, will quit if there's nowhere to return

